kafka:
  brokers: kafka-2435445b-unixfan-c2a5.aivencloud.com:19933
  topic: 'test'
  security_protocol: 'SSL'
  ssl_cafile_path: '../config/ca.pem'
  ssl_certfile_path: '../config/service.cert'
  ssl_keyfile_path: '../config/service.key'
db_items:
  db_host: 'pg-3b80418-unixfan-c2a5.aivencloud.com'
  db_port: 19931
  db_user_name: 'XXX'
  db_password: 'XXX'
  db_name: 'defaultdb'